import { Component, Input, OnInit } from '@angular/core';
import cosmosclient from '@cosmos-client/core';
import { VaultAll200ResponseVaultsInner } from 'ununifi-client/esm/openapi';

export interface OptionConfig {
  name: string;
  route: string;
  description: string;
  image?: string;
}

@Component({
  selector: 'view-yield-aggregator',
  templateUrl: './yield-aggregator.component.html',
  styleUrls: ['./yield-aggregator.component.css'],
})
export class YieldAggregatorComponent implements OnInit {
  @Input()
  symbolMetadataMap?: { [symbol: string]: cosmosclient.proto.cosmos.bank.v1beta1.IMetadata } | null;
  @Input()
  availableSymbols?: string[] | null;
  @Input()
  vaults?: VaultAll200ResponseVaultsInner[] | null;

  configs: OptionConfig[];
  selectedConfig: OptionConfig;
  selectedSymbol?: string;
  selectedDenom?: string | null;

  constructor() {
    this.configs = [
      {
        name: 'Vaults',
        route: 'vaults',
        description:
          'A vault is smart contract that securely holds and manages user funds for the purpose of generating yield through various DeFi strategies.\n\nWhen users deposit their funds into a vault of their choice, the funds are automatically allocated to different yield-generating strategies such as lending, liquidity provision, or farming. The profits generated by these strategies are then distributed back to the users proportional to their share of the total deposits in the vault.',
        image:
          'https://img.freepik.com/free-vector/business-enterprise-strategy-market-analysis-niche-selection-conquering-marketplace-studying-market-segmentation-planning-company-development_335657-2353.jpg',
      },
      {
        name: 'Strategies',
        route: 'strategies',
        description:
          'In DeFi (Decentralized Finance), a strategy is a method or combination of methods employed by a user or aggregator to generate returns on their cryptocurrency holdings.\n\nDeFi protocols typically offer a wide range of financial services, such as lending; borrowing; trading; staking; liquidity providing; yield farming; and more. Therefore, a strategy considers which protocol(s) to use, which asset(s) to hold, how much to allocate, when to rebalance, and how to minimize risks.',
        image:
          'https://img.freepik.com/free-vector/staff-management-perspective-definition-target-orientation-teamwork-organization-business-coach-company-executive-personnel-cartoon-characters_335657-2967.jpg',
      },
    ];
    this.selectedConfig = this.configs[0];
  }

  ngOnInit(): void {}

  onChangeConfig(conf: OptionConfig) {
    this.selectedConfig = conf;
  }

  onChangeSymbol() {
    if (!this.selectedSymbol) {
      return;
    }
    this.selectedDenom = this.symbolMetadataMap?.[this.selectedSymbol].base;
  }
}
