/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export interface InstantiateMsg {
  authority: string;
  denom_swap_contract_map: {
    [k: string]: string;
  };
}
export type ExecuteMsg =
  | {
      update_params: UpdateParamsMsg;
    }
  | {
      deposit_to_vault: DepositToVaultMsg;
    };
export interface UpdateParamsMsg {
  authority?: string | null;
  denom_swap_contract_map?: {
    [k: string]: string;
  } | null;
}
export interface DepositToVaultMsg {
  depositor: string;
  swap_output_denom?: string | null;
  vault_id: string;
}
export type QueryMsg = {
  params: {};
};
export type Addr = string;
export interface Params {
  authority: Addr;
  symbol_swap_contract_map: {
    [k: string]: Addr;
  };
}
