/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  authority: string;
}
export type ExecuteMsg = {
  update_params: UpdateParamsMsg;
} | {
  register_provider: RegisterProviderMsg;
} | {
  update_provider: UpdateProviderMsg;
} | {
  create_verification: CreateVerificationMsg;
} | {
  remove_verification: RemoveVerificationMsg;
};
export interface UpdateParamsMsg {
  authority?: string | null;
}
export interface RegisterProviderMsg {
  address: string;
  details: string;
  identity: string;
  name: string;
  security_contact: string;
  website: string;
}
export interface UpdateProviderMsg {
  address?: string | null;
  details?: string | null;
  id: number;
  identity?: string | null;
  name?: string | null;
  security_contact?: string | null;
  website?: string | null;
}
export interface CreateVerificationMsg {
  customer: string;
  provider_id: number;
}
export interface RemoveVerificationMsg {
  customer: string;
  provider_id: number;
}
export type QueryMsg = {
  params: {};
} | {
  providers: {};
} | {
  verifications: {
    address: string;
  };
};
export type Addr = string;
export interface Params {
  authority: Addr;
}
export type ArrayOfProvider = Provider[];
export interface Provider {
  address: Addr;
  details: string;
  id: number;
  identity: string;
  name: string;
  security_contact: string;
  website: string;
}
export type ArrayOfVerification = Verification[];
export interface Verification {
  address: Addr;
  provider_id: number;
}