import { NFT, NFTClass } from './nft.model';

// Todo: This is dummy data.
export const NFT_CLASSES: NFTClass[] = [
  {
    id: '0x23581767a106ae21c074b2276D25e5C3e136a68b',
    name: 'Good Monkeys',
    symbol: 'GM',
    description: 'Switzerland based artist. Approved creator & ambassador on Sign Art. ...',
    uri: '',
    uri_hash: '',
    data: {
      name: 'Good Monkeys',
      description: 'Switzerland based artist. Approved creator & ambassador on Sign Art. ...',
      image:
        'https://lh3.googleusercontent.com/aJBpzLB_hI3zX_PlcxsJukmbNoikpOJrhtJUrz7q6XXbsBD59r7LHQq7vmusTtVn9ex4WsQf1KFzz_fXy8FkovvDwOErH5IMNWSlsA=s0',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    id: '0x23581767a106ae21c074b2276D25e5C3e136a68b',
    name: 'The Raven',
    symbol: 'TR',
    description: 'Tom Sachs Rocket Factory is a trans-dimensional manufacturing plant: ...',
    uri: '',
    uri_hash: '',
    data: {
      name: 'The Raven',
      description: 'Tom Sachs Rocket Factory is a trans-dimensional manufacturing plant: ...',
      image:
        'https://lh3.googleusercontent.com/dajx50F-VzEd3YeUMmZhKWPy42X7vq0d4Emqe7BB2c5XDYToFgpbi_VlmpHMofZJ6RVi7VEJ-G_WAH3D0MN48fAmAV0Uq2S1iY_yAQs=s0',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    id: '0x23581767a106ae21c074b2276D25e5C3e136a68b',
    name: 'SushiCats',
    symbol: 'SC',
    description: 'S5,555 collectibles of Modern Anime Aesthetics bring you into the world ...',
    uri: '',
    uri_hash: '',
    data: {
      name: 'SushiCats',
      description: 'S5,555 collectibles of Modern Anime Aesthetics bring you into the world ...',
      image:
        'https://lh3.googleusercontent.com/Rdy4rpIQwSk5Gdzxc0HueX9pXARDtz9J2ifBXBus2n-eLzqu-3xTh1nC24Nl8Uh857Wk7Ax9QUbWuHANqp0dMlRNWYIuhltLoJBTag=s0',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    id: '0x23581767a106ae21c074b2276D25e5C3e136a68b',
    name: 'HAPE',
    symbol: 'HAPE',
    description: '8192 next-generation, high-fashion HAPES.',
    uri: '',
    uri_hash: '',
    data: {
      name: 'HAPE',
      description: '8192 next-generation, high-fashion HAPES.',
      image:
        'https://lh3.googleusercontent.com/aJBpzLB_hI3zX_PlcxsJukmbNoikpOJrhtJUrz7q6XXbsBD59r7LHQq7vmusTtVn9ex4WsQf1KFzz_fXy8FkovvDwOErH5IMNWSlsA=s0',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    id: '0x23581767a106ae21c074b2276D25e5C3e136a68b',
    name: 'DeadFellaz',
    symbol: 'DF',
    description: 'A collection of 10,000 undead NFTs minted on the Ethereum blockchain. ...',
    uri: '',
    uri_hash: '',
    data: {
      name: 'DeadFellaz',
      description: 'A collection of 10,000 undead NFTs minted on the Ethereum blockchain. ...',
      image:
        'https://lh3.googleusercontent.com/nNcKiB6MuhxWlfWs5uyTSD3xra3cmaC5lSUCMJFYhcyL7rMelQtEKr1f_eJU5HFBKS-DHhMnBRowyTkKm12NaSFLP38FyiupkAXbTv8=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    id: '0x23581767a106ae21c074b2276D25e5C3e136a68b',
    name: 'Moments on Film',
    symbol: 'MOF',
    description: 'Location: Iceland Filmstock: Kodak Portra 800',
    uri: '',
    uri_hash: '',
    data: {
      name: 'Moments on Film',
      description: 'Location: Iceland Filmstock: Kodak Portra 800',
      image:
        'https://lh3.googleusercontent.com/s0Hq5cB-8WjMM9Q-SZwEOwXksVOf_EfG9aj1KGfoQhtTgHHkkHXfksV1XXa-eDPPlN3XTr1i513g7RnOYG340nqTO5hpgCZvGyCo=s0',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
];

// Todo: This is dummy data.
export const NFTS: NFT[] = [
  {
    nft_class: NFT_CLASSES[0],
    id: '1',
    uri: '',
    uri_hash: '',
    data: {
      name: 'Good Monkeys',
      description: 'Switzerland based artist. Approved creator & ambassador on Sign Art. ...',
      image:
        'https://lh3.googleusercontent.com/1EVmMZzJyHZkN7B6Hgq2BRz4GTfkuJH0AVPaaBTM2jpDtu6N_eIbsD7LizOmyielZQxmKwaZTBG7_x-kC9_T6AMqIFvQ3JnaNYRm=s550',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[0],
    id: '2',
    uri: '',
    uri_hash: '',
    data: {
      name: 'The Raven',
      description: 'Tom Sachs Rocket Factory is a trans-dimensional manufacturing plant: ...',
      image:
        'https://lh3.googleusercontent.com/wzHle0nGsxzq0tPRevPGkmWMAHQeF_QDtUg6fed7R610wb--1ubSx6C5l4sLnF-QDR4PX6cMaLTWFht36AzpkFSV9TmJQvAZ8PKl=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[0],
    id: '3',
    uri: '',
    uri_hash: '',
    data: {
      name: 'SushiCats',
      description: 'S5,555 collectibles of Modern Anime Aesthetics bring you into the world ...',
      image:
        'https://lh3.googleusercontent.com/V7CBs320JUMkH5RPmouMLL-4ZhYn0tSNanRPlUxA6RUCLzOTYQoghZ0D5tfevOvTonulbFxWGDWxP1EqT0NH2ABD9OQH4PPDCf696Jk=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[0],
    id: '4',
    uri: '',
    uri_hash: '',
    data: {
      name: 'HAPE',
      description: '8192 next-generation, high-fashion HAPES.',
      image:
        'https://lh3.googleusercontent.com/Tx1kHuEvnVdYUJ3gP0fRYeZgqtZflJk312AEphyHYd9wRbWYo3X9V6htuD0ZCeLrUwRAtgyrt4sp9LAvUQ5AAiW2gjZz6ut8Uy1A=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[0],
    id: '5',
    uri: '',
    uri_hash: '',
    data: {
      name: 'DeadFellaz',
      description: 'A collection of 10,000 undead NFTs minted on the Ethereum blockchain. ...',
      image:
        'https://lh3.googleusercontent.com/nNcKiB6MuhxWlfWs5uyTSD3xra3cmaC5lSUCMJFYhcyL7rMelQtEKr1f_eJU5HFBKS-DHhMnBRowyTkKm12NaSFLP38FyiupkAXbTv8=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[0],
    id: '6',
    uri: '',
    uri_hash: '',
    data: {
      name: 'Moments on Film',
      description: 'Location: Iceland Filmstock: Kodak Portra 800',
      image:
        'https://lh3.googleusercontent.com/kYjRVe-j-DkzUg5ghCLt4Mtfgp68invaBj_AiunH_l9mLwmwpBli53Z7_A8HTwiJ3CdZir_OB3jRlf4AeSYSdy4bwEaZB1BsIWwPdQ=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[1],
    id: '1',
    uri: '',
    uri_hash: '',
    data: {
      name: 'Good Monkeys',
      description: 'Switzerland based artist. Approved creator & ambassador on Sign Art. ...',
      image:
        'https://lh3.googleusercontent.com/1EVmMZzJyHZkN7B6Hgq2BRz4GTfkuJH0AVPaaBTM2jpDtu6N_eIbsD7LizOmyielZQxmKwaZTBG7_x-kC9_T6AMqIFvQ3JnaNYRm=s550',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[1],
    id: '2',
    uri: '',
    uri_hash: '',
    data: {
      name: 'The Raven',
      description: 'Tom Sachs Rocket Factory is a trans-dimensional manufacturing plant: ...',
      image:
        'https://lh3.googleusercontent.com/wzHle0nGsxzq0tPRevPGkmWMAHQeF_QDtUg6fed7R610wb--1ubSx6C5l4sLnF-QDR4PX6cMaLTWFht36AzpkFSV9TmJQvAZ8PKl=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[1],
    id: '3',
    uri: '',
    uri_hash: '',
    data: {
      name: 'SushiCats',
      description: 'S5,555 collectibles of Modern Anime Aesthetics bring you into the world ...',
      image:
        'https://lh3.googleusercontent.com/V7CBs320JUMkH5RPmouMLL-4ZhYn0tSNanRPlUxA6RUCLzOTYQoghZ0D5tfevOvTonulbFxWGDWxP1EqT0NH2ABD9OQH4PPDCf696Jk=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[1],
    id: '4',
    uri: '',
    uri_hash: '',
    data: {
      name: 'HAPE',
      description: '8192 next-generation, high-fashion HAPES.',
      image:
        'https://lh3.googleusercontent.com/Tx1kHuEvnVdYUJ3gP0fRYeZgqtZflJk312AEphyHYd9wRbWYo3X9V6htuD0ZCeLrUwRAtgyrt4sp9LAvUQ5AAiW2gjZz6ut8Uy1A=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[1],
    id: '5',
    uri: '',
    uri_hash: '',
    data: {
      name: 'DeadFellaz',
      description: 'A collection of 10,000 undead NFTs minted on the Ethereum blockchain. ...',
      image:
        'https://lh3.googleusercontent.com/nNcKiB6MuhxWlfWs5uyTSD3xra3cmaC5lSUCMJFYhcyL7rMelQtEKr1f_eJU5HFBKS-DHhMnBRowyTkKm12NaSFLP38FyiupkAXbTv8=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
  {
    nft_class: NFT_CLASSES[1],
    id: '6',
    uri: '',
    uri_hash: '',
    data: {
      name: 'Moments on Film',
      description: 'Location: Iceland Filmstock: Kodak Portra 800',
      image:
        'https://lh3.googleusercontent.com/kYjRVe-j-DkzUg5ghCLt4Mtfgp68invaBj_AiunH_l9mLwmwpBli53Z7_A8HTwiJ3CdZir_OB3jRlf4AeSYSdy4bwEaZB1BsIWwPdQ=w600',
      image_data: '',
      external_url: '',
      animation_url: '',
      youtube_url: '',
      background_color: '',
      attributes: [],
    },
  },
];
